# Generated by Django 4.2.4 on 2023-08-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_product_image3_product_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count39',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='count40',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='count41',
            field=models.IntegerField(default=0),
        ),
    ]
