# Generated by Django 4.2.4 on 2023-09-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_order_address_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
