# Generated by Django 4.2.4 on 2023-09-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='category_slide',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
