# Generated by Django 5.0 on 2024-05-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count39',
        ),
        migrations.RemoveField(
            model_name='product',
            name='count40',
        ),
        migrations.RemoveField(
            model_name='product',
            name='count41',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
    ]
